/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author thiennd
 */
public class GetKeyForm extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form GetKeyForm
     */
    public static final int UP = 1;
    public static final int DOWN = 2;
    public static final int LEFT = 3;
    public static final int RIGHT = 4;
    public static final int FIRE = 5;
    public static final int PAUSE = 6;
    SettingFrame sf;
    int currentKey = -1;
    int type = 1;

    public GetKeyForm(SettingFrame sf) {
        this.sf = sf;
        initComponents();
        addKeyListener(this);
        setLocationRelativeTo(sf);
    }

    public void setVisible(boolean vis, int type) {
        this.setVisible(vis);
        this.type = type;
    }

    public void setKey(int keycode) {
        if (keycode == KeyEvent.VK_ESCAPE) {
            this.setVisible(false);
            sf.showControlSetting();
            return;
        }
        switch (type) {
            case UP:
                ENV.setting.keyUp = keycode;
                break;
            case DOWN:
                ENV.setting.keyDown = keycode;
                break;
            case LEFT:
                ENV.setting.keyLeft = keycode;
                break;
            case RIGHT:
                ENV.setting.keyRight = keycode;
                break;
            case FIRE:
                ENV.setting.keyFire = keycode;
                break;
            case PAUSE:
                ENV.setting.keyPause = keycode;
                break;
        }
        this.setVisible(false);
        sf.showControlSetting();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Press any key, Esc to cancel...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        setKey(ke.getKeyCode());
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
